powerdata <- read.table("household_power_consumption.txt",sep = ";",header = TRUE,na.strings = "?",stringsAsFactors = FALSE)
powerdata$DateDate <- as.Date(powerdata$Date,format='%d/%m/%Y')
startdate <- as.Date("2007-02-01")
enddate <- as.Date("2007-02-02")
febdata <- powerdata[which(powerdata$DateDate >= startdate & powerdata$DateDate <= enddate),]
febdata$DateTime <- strptime(paste(febdata$Date,febdata$Time), "%d/%m/%Y %H:%M:%S")

png("plot4.png")
par(mfrow=c(2,2))
plot(febdata$DateTime,febdata$Global_active_power,type="l",xlab = "",ylab = "Global Active Power")
plot(febdata$DateTime,febdata$Voltage,type="l",xlab = "datetime",ylab = "Voltage")
plot(febdata$DateTime,febdata$Sub_metering_1,type="l",xlab = "",ylab = "Energy sub metering")
lines(febdata$DateTime,febdata$Sub_metering_2,col="red")
lines(febdata$DateTime,febdata$Sub_metering_3,col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty = c(1,1,1),bty="n")
plot(febdata$DateTime,febdata$Global_reactive_power,type="l",xlab = "datetime",ylab = "Global_reactive_power")
dev.off()